### ISSUE TITLE
NAudio dll missing

### ISSUE THREAD

**Issue by hicode-and** [kolod/modalarm#2]
Hello,
I have downloaded and installed modalarm, but i have an issue.
When i want to add an alarm and save a i have an error message. 

<a href="https://ibb.co/T1s2Lmp"><img src="https://i.ibb.co/m03T861/modAlarm.png" alt="modAlarm" border="0"></a>

It say NAudio assembly is missing but i have, and i have unblocked it.

Thanks

**Comment by kolod** [comment]
Hello!
What versions of the operating system and RapidSCADA do you use?


------ Исходное сообщение ------
От: "Lacommunitedelinfo" <notifications@github.com>
Кому: "kolod/modalarm" <modalarm@noreply.github.com>
Копия: "Subscribed" <subscribed@noreply.github.com>
Отправлено: 14.04.2020 18:07:09
Тема: [kolod/modalarm] NAudio dll missing (#2)

**Comment by hicode-and** [comment]
Hello, i use the latest RapidScada (5.8.0) and my VM is under Windows 7 :)

**Comment by kolod** [comment]
Hello!
Please test the new version 
<https://1drv.ms/u/s!AvPj3KWZV-2_jaBvLJwgYD8Sc5vCxg?e=AnwKJS>.

**Comment by hicode-and** [comment]
Hello !
With this version it seem to work ! Nice thanks you
